name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "master","render" ]
    paths:
      - 'Backend/**'  # Case-sensitive!

env:
  DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
  DATASOURCE_USER: ${{ secrets.DATASOURCE_USER }}
  DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      working-directory: ./Backend
      run: mvn clean package -DskipTests
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      working-directory: ./Backend
      run: |
        docker build -t tahsin599/bizbooker-backend:latest .
        docker push tahsin599/bizbooker-backend:latest
        
 