name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Backend/**'  # Case-sensitive!

env:
  DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
  DATASOURCE_USER: ${{ secrets.DATASOURCE_USER }}
  DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      working-directory: ./Backend
      run: mvn clean package -DskipTests
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      working-directory: ./Backend
      run: |
        docker build -t tahsin599/bizbooker-backend:latest .
        docker push tahsin599/bizbooker-backend:latest
        
    - name: Update Render Environment Variables
      run: |
        curl -X PATCH \
          "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/env-vars" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '[
            {"key": "DATASOURCE_URL", "value": "${{ secrets.DATASOURCE_URL }}"},
            {"key": "DATASOURCE_USER", "value": "${{ secrets.DATASOURCE_USER }}"},
            {"key": "DATASOURCE_PASSWORD", "value": "${{ secrets.DATASOURCE_PASSWORD }}", "sync": true},
            {"key": "FRONTEND_URL", "value": "${{ secrets.FRONTEND_URL }}"}
          ]'
    
    - name: Update Render Image
      run: |
        curl -X PATCH \
          "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "image": {
              "owner": "tahsin599",
              "name": "bizbooker-backend",
              "tag": "latest"
            }
          }'
        
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}