name: Deploy to Azure VM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
      
      - name: Add Azure VM to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts

      - name: Configure Docker permissions on Azure VM
        run: |
          ssh ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} << 'EOF'
          # Ensure Docker is running
          sudo systemctl start docker || sudo systemctl enable --now docker
          
          # Add user to docker group (if not already)
          sudo usermod -aG docker $USER || true
          
          # Apply group changes immediately
          newgrp docker << 'INNER_EOF'
          # Verify Docker access
          docker info || exit 1
          INNER_EOF
          EOF

      - name: Set up Docker context for remote host
        run: |
          # Force remove existing context
          docker context rm -f azure-vm 2>/dev/null || true
          
          # Create new context
          docker context create azure-vm \
            --docker "host=ssh://${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }}"
          
          # Verify connection
          docker --context azure-vm info || (echo "::error::Docker connection failed"; exit 1)
      
      - name: Deploy with docker-compose
        run: |
          docker --context azure-vm compose -f docker-compose.deploy.yml down --remove-orphans --timeout 1 || true
          docker --context azure-vm compose -f docker-compose.deploy.yml pull
          docker --context azure-vm compose -f docker-compose.deploy.yml up --build -d --wait
      
      - name: Verify deployment
        run: |
          docker --context azure-vm compose -f docker-compose.deploy.yml ps
          docker --context azure-vm compose -f docker-compose.deploy.yml logs --tail=20
          echo "✅ Deployment successful"
      
      - name: Reset Docker context
        if: always()
        run: |
          docker context use default
          docker context rm -f azure-vm 2>/dev/null || true

