name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      
      - 'bizbooker_frontend/**'  # Additional path you mentioned
      

env:
  DOCKER_IMAGE: "tahsin599/bizbooker-frontend"  # Change to your Docker Hub repo
  DOCKER_TAG: "latest"  # Or use ${{ github.sha }} for unique tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      working-directory: ./bizbooker_frontend  # Change if your Dockerfile is elsewhere
      run: |
        docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
        docker push $DOCKER_IMAGE:$DOCKER_TAG
        
    - name: Verify push
      run: |
        echo "Successfully pushed $DOCKER_IMAGE:$DOCKER_TAG to Docker Hub"